### ISSUE TITLE
Bun latest version

### ISSUE THREAD

**Issue by KevinBonnoron** [nhaef/devcontainer-bun#1]
Hello !

Could you please launch a build to update bun version (1.1.28) to latest please?

Regards

**Comment by nhaef** [comment]
Hi @KevinBonnoron,

thanks for opening the issue. I have created a few new image versions for Bun versions up and including `1.1.30`. Could you please let me know if everything works as expected?

```jsonc
{
    "name": "Bun",
    "image": "ghcr.io/nhaef/devcontainer-bun:latest"
}
```

Best Regards

**Comment by KevinBonnoron** [comment]
It's working great. Thank you for your quick response.

Regards

**Comment by KevinBonnoron** [comment]
Hello @nhaef ,

May I ask you to launch a new build with latest release please?

Kind regards.

**Comment by nhaef** [comment]
Hi @KevinBonnoron,

thanks for the reminder. I have created new builds for `1.2.7` to `1.2.18`. Just let me know in case there are any issues. Thanks!

Best regards

**Comment by KevinBonnoron** [comment]
Thanks for you very quick response! It's working.
Have a great day!

Regards
